name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install libpq-dev && rustup update

    - name: Clippy
      run: cargo clippy

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: |
        mkdir -p ${AWS_CONFIG_FILE} && \
        echo [default] > ${AWS_CONFIG_FILE}/config && \
        echo region = us-east-1 >> ${AWS_CONFIG_FILE}/config && \
        echo [default] > ${AWS_CONFIG_FILE}/credentials && \
        echo aws_access_key_id = ${AWS_ACCESS_KEY_ID} >> ${AWS_CONFIG_FILE}/credentials && \
        echo aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY} >> ${AWS_CONFIG_FILE}/credentials && \
        cargo test --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-1
        AWS_CONFIG_FILE: ${HOME}/.aws

    - name: Generate code coverage
      run: |
        cargo install cargo-tarpaulin && \
        cargo build && \
        cargo tarpaulin --verbose --all-features --workspace --out Xml
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-1
        AWS_CONFIG_FILE: /tmp/.aws

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
